### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by lshin** [Spoowy/ElasticSearch#1]
If you're using a case sensitive filesystem like unix or linux, this package is broken to find a class.
Could you change the following directory and filename to keep a same as package namespace?

src/Spoowy/ElasticSearch/ElasticSearchServiceProvider.php -> src/Spoowy/**Elasticsearch**/**ElasticsearchServiceProvider.php**

**Comment by Spoowy** [comment]
Thank you. Yes of course

**Comment by lshin** [comment]
Awesome. Thanks!
